[[edge_functions]]
  function = "auth"
  path = "/auth/*"

[[edge_functions]]
  function = "files"
  path = "/fileByCid"
  
[[edge_functions]]
  function = "files"
  path = "/filesByTags"
  
[[edge_functions]]
  function = "files"
  path = "/create/group"
  
[[edge_functions]]
  function = "files"
  path = "/update/file"
  
[[edge_functions]]
  function = "files"
  path = "/pendingFilesByOwner"
  
[[edge_functions]]
  function = "files"
  path = "/filesByOwnerByNextPageToken"
  
[[edge_functions]]
  function = "files"
  path = "/delete/file"

[[edge_functions]]
  function = "files"
  path = "/fileByAssetAddress"

[[edge_functions]]
  function = "files"
  path = "/freeFileByAddress"

[[edge_functions]]
  function = "pinata"
  path = "/presigned_url/*"
  
[[edge_functions]]
  function = "pinata"
  path = "/groupByName/*"

[[edge_functions]]
  function = "index"
  path = "/"

[[edge_functions]]
  function = "index"
  path = "/webhook"

[build.environment]
  # Environment variables for Edge Functions
  # Note: You need to set these in Netlify's dashboard or via CLI
  # For local development, they should be in your .env file